"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { FileText, Download, Plus, Calendar } from "lucide-react";
import Topbar from "@/components/layout/Topbar";
import { db } from "@/lib/db";
import { formatCurrency, todayISO } from "@/lib/utils";
import { useAuth } from "@/lib/auth-context";
import { queueLocalMutation } from "@/lib/sync";
import { v4 as uuidv4 } from "uuid";
import type { Sale, Product, Statement } from "@/types";

interface DailyData {
  date: string;
  totalSales: number;
  cashReceived: number;
  creditExtended: number;
  salesCount: number;
}

export default function StatementsPage() {
  const { business } = useAuth();
  const [data, setData] = useState<DailyData[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    if (business) {
      loadData(business.id);
    }
  }, [business]);

  async function loadData(businessId: string) {
    const allSales = await db.sales.where("business_id").equals(businessId).toArray();

    const byDay: Record<string, Sale[]> = {};
    allSales.forEach((s) => {
      const d = (s.created_at ?? todayISO()).split("T")[0];
      if (!byDay[d]) byDay[d] = [];
      byDay[d].push(s);
    });

    const rows: DailyData[] = Object.keys(byDay)
      .sort((a, b) => b.localeCompare(a))
      .slice(0, 30)
      .map((date) => {
        const sales = byDay[date];
        const totalSales = sales.reduce((s, x) => s + x.total, 0);
        const cashReceived = sales.filter((x) => x.payment_type !== "Credit").reduce((s, x) => s + x.total, 0);
        const creditExtended = sales.filter((x) => x.payment_type === "Credit").reduce((s, x) => s + x.total, 0);
        return { date, totalSales, cashReceived, creditExtended, salesCount: sales.length };
      });

    setData(rows);
    setLoading(false);
  }

  async function generateDailyStatement(row: DailyData) {
    const html = `
      <html>
      <head>
        <title>Daily Statement - ${row.date}</title>
        <style>
          body { font-family: 'Segoe UI', sans-serif; margin: 0; padding: 40px; color: #111; }
          .header { border-bottom: 3px solid #16a34a; padding-bottom: 16px; margin-bottom: 24px; }
          .header h1 { font-size: 24px; color: #16a34a; margin: 0; }
          .header p { color: #666; font-size: 13px; margin: 4px 0 0; }
          .section { background: #f9fafb; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
          .section h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; margin: 0 0 12px; }
          .row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #e5e7eb; }
          .row:last-child { border: none; font-weight: bold; }
          .label { color: #374151; font-size: 14px; }
          .value { font-size: 14px; font-weight: 600; }
          .green { color: #16a34a; }
          .red { color: #dc2626; }
          .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #9ca3af; }
        </style>
      </head>
      <body>
        <div class="header">
          ${business?.logo_url ? `<img src="${business.logo_url}" alt="Logo" style="height:48px; border-radius:8px; margin-bottom:12px; display:block;" />` : ''}
          <h1>Daily Business Statement</h1>
          <p>Business: ${business?.name || "StoreOS Business"}</p>
          <p>Date: ${new Date(row.date).toLocaleDateString("en-NG", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}</p>
          <p>Generated by StoreOS</p>
        </div>
        <div class="section">
          <h2>Sales Summary</h2>
          <div class="row"><span class="label">Total Transactions</span><span class="value">${row.salesCount}</span></div>
          <div class="row"><span class="label">Total Revenue</span><span class="value green">${formatCurrency(row.totalSales)}</span></div>
        </div>
        <div class="section">
          <h2>Cash Flow</h2>
          <div class="row"><span class="label">Cash & Transfer Received</span><span class="value green">${formatCurrency(row.cashReceived)}</span></div>
          <div class="row"><span class="label">Credit Extended</span><span class="value red">${formatCurrency(row.creditExtended)}</span></div>
          <div class="row"><span class="label">Net Cash Position</span><span class="value green">${formatCurrency(row.cashReceived)}</span></div>
        </div>
        <div class="footer">StoreOS — University Tech Hub · This is an official business record</div>
      </body>
      </html>
    `;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `statement-${row.date}.html`;
    a.click();
    URL.revokeObjectURL(url);

    if (business) {
      const statementId = uuidv4();
      const statementRecord: Statement = {
        id: statementId,
        business_id: business.id,
        period_start: row.date,
        period_end: row.date,
        type: "daily",
        data_json: row,
        created_at: new Date().toISOString(),
      };
      
      try {
        await db.statements.add(statementRecord);
        await queueLocalMutation('statements', 'insert', statementId, statementRecord);
      } catch (e) {
        console.error("Failed to save statement record", e);
      }
    }
  }

  return (
    <div className="animate-fade-in">
      <Topbar title="Statements" />
      <div className="px-4 lg:px-6 py-5 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-gray-900">Business Statements</h2>
            <p className="text-sm text-gray-500">Auto-generated daily records</p>
          </div>
        </div>

        {/* Banner */}
        <div className="bg-gradient-to-r from-green-600 to-green-700 rounded-2xl p-5 text-white">
          <div className="flex items-start gap-3">
            <FileText className="w-8 h-8 shrink-0 opacity-80" />
            <div>
              <p className="font-bold text-lg">Your Statements Are Ready</p>
              <p className="text-sm text-green-100 mt-1">Download formal, bank-ready daily statements from your recorded sales. No manual work needed.</p>
            </div>
          </div>
        </div>

        {loading ? (
          <div className="space-y-2">
            {[...Array(4)].map((_, i) => <div key={i} className="card p-4 animate-pulse h-20" />)}
          </div>
        ) : data.length === 0 ? (
          <div className="card p-10 text-center">
            <FileText className="w-12 h-12 text-gray-200 mx-auto mb-3" />
            <p className="text-gray-500 font-medium">No statements yet</p>
            <p className="text-sm text-gray-400 mt-1">Statements are generated from your sales records.</p>
            <Link href="/dashboard/sales/new" className="mt-4 inline-block btn-primary text-sm">
              Record a Sale
            </Link>
          </div>
        ) : (
          <div className="space-y-2">
            {data.map((row) => (
              <div key={row.date} className="card p-4 flex items-center gap-4">
                <div className="w-10 h-10 rounded-xl bg-purple-50 flex items-center justify-center shrink-0">
                  <Calendar className="w-5 h-5 text-purple-600" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-gray-900">
                    {new Date(row.date).toLocaleDateString("en-NG", { weekday: "short", day: "numeric", month: "long", year: "numeric" })}
                  </p>
                  <p className="text-xs text-gray-500">
                    {row.salesCount} sales · Cash: {formatCurrency(row.cashReceived)} · Credit: {formatCurrency(row.creditExtended)}
                  </p>
                </div>
                <div className="text-right shrink-0">
                  <p className="text-sm font-bold text-green-700">{formatCurrency(row.totalSales)}</p>
                  <button
                    onClick={() => generateDailyStatement(row)}
                    className="flex items-center gap-1 text-xs text-gray-500 hover:text-green-600 mt-1 transition-colors"
                  >
                    <Download className="w-3 h-3" /> Download
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
